### ISSUE TITLE
nativeTransitionsBack not working

### ISSUE THREAD

**Issue by neslinesli93** [shprink/ionic-native-transitions#105]
I am implementing a search state, and this is roughly the definition
```
.state('main.search', {
    url: '/search',
    nativeTransitions: null,
    nativeTransitionsBack: null,
    // Same result with nativeTransitionsBackAndroid: null
    views: {
        'view-content': {
            templateUrl: 'main/templates/search.html',
            controller: 'SearchCtrl'
        }
    }
})
```

The property nativeTransitions works like a charm, however nativeTransitionsBack is completely ignored and instead I get the default transition (slide).
I've tried to use the hardware back button (testing on Android), or to call `$ionicNativeTransitions.goBack();`however, all I get is the slide transition.
Is this a bug or I am doing something wrong?
Thanks

**Comment by kshaaban-** [comment]
I'm also facing the same issue when directly calling any of:

```
$ionicHistory.goBack();
$ionicNativeTransitions.goBack();
$rootScope.$ionicGoBack();
```

But it works fine when using ionic's `<ion-nav-back-button>` directive. Unfortunately, the current app i'm working on doesn't use a `<ion-nav-bar>`.

I'll try to do some investigation on this

**Comment by neslinesli93** [comment]
Thank you so much for the quick response, will try this later!

**Comment by shprink** [comment]
I put the fix in a branch for now. I am having trouble using the latest crosswalk. As soon as it works I will release v1.0.0

**Comment by toralwang** [comment]
setting backInOppositeDirection=true

 $ionicNativeTransitionsProvider.setDefaultOptions({
            ...
            backInOppositeDirection: true // Takes over default back transition and state back transition to use the opposite direction transition to go back
        });

$ionicNativeTransitions.goBack()  Can work properly

**Comment by kmturley** [comment]
This is a workaround that works in the current build for android:

    .state('edit', {
        url: '/edit',
        nativeTransitions: null,
        nativeTransitionsBackAndroid: {
            duration: 0
        },
        templateUrl: 'components/edit/edit.html',
        controller: 'Edit'
    })

**Comment by Tronix117** [comment]
I have the same issue, whatever I change it doesn't work, the back transition is same as forward.
I tried, `native-ui-sref-, `native-options`, `native-ui-sref-opts`, `nav-direction`, `backInOppositeDirection: true`, `$ionicNativeTransitions.goBack()`, `$ionicHistory.goBack()`, `$ionicGoBack()`...

I always have the default "slide left" transition instead of "slide right" on iOS and Android without XWALK. With the exception of the hardware back button which have the correct behavior.

Even with a :
```
$ionicNativeTransitionsProvider.setDefaultBackTransition({
      type: 'flip'
      direction: 'right'
})
```
It doesn't change anything even the hardware button keep the same behavior.

Any ideas? I even used the bug/105 branch without more success.
I am on Ionic 3.1.1, telerik native transitions 0.6.5
