### ISSUE TITLE
Transitions in beta5

### ISSUE THREAD

**Issue by scottopolis** [shprink/ionic-native-transitions#13]
I updated to beta5, and removed all of the native-transition directives in the markup.  I'm having trouble controlling when the native transition happens.

For example, it works on my post list at first. But if I click to another state, then go back, it stops using native transitions.

I don't want native transitions when a menu item is clicked, so I added this:

    .state('app', {
    url: "/app",
    abstract: true,
    template: require("./templates/menu.html"),
    nativeTransitions: null,
    controller: 'AppCtrl'
    })

That didn't work, it still uses the transition.

My config file looks like this:

    $ionicNativeTransitionsProvider.setDefaultOptions({
    "duration"          : 300,
    "androiddelay"      : 100, // Longer delay better for older androids
    // "fixedPixelsTop"    : 64, // looks OK on iOS
    });

    $ionicNativeTransitionsProvider.setDefaultTransition({
      type: 'slide',
      direction: 'left'
    });

    $ionicNativeTransitionsProvider.setDefaultBackTransition({
      type: 'slide',
      direction: 'right'
    });

**Comment by shprink** [comment]
Several things here.

Beta5 embraces Telerik plugin 4.3, if you are still in 4.2 you will need to upgrade.

The `setDefaultOptions. androiddelay ` and `setDefaultOptions. iosdelay ` are set to -1 by default which is a new Telerik feature. What it does is instead of setting delay to wait before animating to the new view, you need to trigger it manually. The problem was that delays are not a solution as it differ from device to device. This is automated in this plugin using Ui router events.

This new feature only works on slide transitions (on android) but will be support all transitions hopefully in next version. What I can see is that it works fine on iOS and is unstable on Android for now.

A work around for android is to set the delay to 0 or greater:

```
$ionicNativeTransitionsProvider.setDefaultOptions({
        androiddelay: 0
    });
```

If you want to disable native transition on a specific state you can using `nativeTransitions: null` but not on abstract states (which is your case).

Sorry if it is confusing, waiting for Telerik's new release to have something stable on all use cases hopefully.

**Comment by shprink** [comment]
Telerik's plugin 0.5 just got released!!! https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/78#issuecomment-149570054

I will need few days to test and release beta6. stay tuned

**Comment by shprink** [comment]
actually beta6 is out. Have not tested fully yet.

**Comment by scottopolis** [comment]
Thanks Julien, updating and removing the androiddelay worked everything out.  I still need to be able to deactivate transitions on abstract states, but I'll wait until you add that in a future version.
