### ISSUE TITLE
Failed to instantiate module ionic-native-transitions

### ISSUE THREAD

**Issue by amitpatil321** [shprink/ionic-native-transitions#52]
I did below 3 steps

1) ionic plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5

2) angular.module('yourApp', [
    'ionic-native-transitions'
]);

3) .config(function($ionicNativeTransitionsProvider){
    $ionicNativeTransitionsProvider.setDefaultTransition({
        type: 'slide',
        direction: 'left'
    });
});

and now i am getting error 

$injector:modulerr] Failed to instantiate module starter due to:
[$injector:modulerr] Failed to instantiate module ionic-native-transitions due to:
[$injector:nomod] Module 'ionic-native-transitions' is not available! 

Plugin has been installed successfully, when i list all plugins i see it in list. 
What could have gone wrong ?

$injector:modulerr] Failed to instantiate module starter due to:
[$injector:modulerr] Failed to instantiate module ionic-native-transitions due to:
[$injector:nomod] Module 'ionic-native-transitions' is not available!

**Comment by kewix** [comment]
What is your version of Ionic ?

**Comment by amitpatil321** [comment]
Cordova CLI: 5.4.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v0.12.2

**Comment by shprink** [comment]
You simply forgot to use this lib.. Check this issue: https://github.com/shprink/ionic-native-transitions/issues/29

**Comment by stefanotauriello** [comment]
I have installed using both Cordova and Ionic CLI but when i add 'ionic-native-transitions' in angular.module, it doesn't find the module.

How can I resolve this?

Thanks

**Comment by cotufaloschiflones** [comment]
@stefanotauriello @amitpatil321 @shprink 
I had the same problem. It's very important to know if you are using a scaffolding tool (I use the generator-ionic-gulp). Recently they changed "the way" of the compiling process, see this link (point 2).
https://www.npmjs.com/package/generator-ionic-gulp#development-mode

Previously the export of the final vendor.js file (with all the dependencies) came from vendor.json and now it came from bower.json. So in order to work properly you must to update that file :)

**Comment by AhsanSN** [comment]
happened to me once. do check your app.js for syntax errors.
