### ISSUE TITLE
See next Screen, before slide in

### ISSUE THREAD

**Issue by rails-master** [shprink/ionic-native-transitions#78]
Behaviour on iOS real device - it not happens on the emulator:
When i tap a link (view A), it shows directly the next view ( view B). Than the transitions starts and slides B out and slides B in - Finally it shows view B.

However, during the transition the starting view A is not visible.

Have someone this problem also?

**Comment by harellevy** [comment]
+1 same here, ionic with crosswalk, same issue

**Comment by jeremygomez** [comment]
+1

I just started seeing this issue (iOS simulator AND device) when i updated Ionic from 1.2.1 to the latest nightly 1.2.4 build. I was not seeing it before.

**Comment by jeremygomez** [comment]
To expand a bit on my previous statement, it looks like changes made specifically in Ionic **1.2.4-nightly-2811** causes this issue (**1.2.4-nightly-2775** works fine). After digging in a bit, I have found that removing the following line in ionic-angular.js fixes the issue...

```
css.opacity = opacity;
```

Not sure what that means yet for any potential fix to the ionic-native-transitions code though.

**Comment by karjajuu** [comment]
I had the same issue and debugged it a little bit. I found a solution which is to add a timeout to the state change in the stateGo() function in the ionic.native-transitions(.min).js which leads to it being run as the last function. The following code works on both iOS and Android devices.

`function stateGo() {
	            var state = arguments.length <= 0 || arguments[0] === undefined ? null : arguments[0];
	            var stateParams = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];
	            var transitionOptions = arguments.length <= 2 || arguments[2] === undefined ? null : arguments[2];
	            var stateOptions = arguments.length <= 3 || arguments[3] === undefined ? {} : arguments[3];

	            if (!state) {
	                $log.debug('[native transition] cannot change state without a state...');
	                return;
	            }
	            unregisterToStateChangeStartEvent();
							transition(transitionOptions);
							if (ionic.Platform.isIOS()) {
		            $timeout(function() {
									$state.go(state, stateParams, stateOptions);
								});
							} else {
								$state.go(state, stateParams, stateOptions);
							}
	        }` 

I decided to add the check for an iOS device and run the timeout only in that case because it was only occurring in iOS devices and the timeout perhaps made Android devices flicker a little on the transition (I could be paranoid and this not really even occurring, or is due to large images on the content on my app).

**Comment by thepi0** [comment]
I had the same issue and debugged it a little bit. I found a solution which is to add a timeout to the state change in the stateGo() function in the ionic.native-transitions(.min).js which leads to it being run as the last function. The following code works on both iOS and Android devices.

```
function stateGo() {
  var state = arguments.length <= 0 || arguments[0] === undefined ? null : arguments[0];
  var stateParams = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];
  var transitionOptions = arguments.length <= 2 || arguments[2] === undefined ? null : arguments[2];
  var stateOptions = arguments.length <= 3 || arguments[3] === undefined ? {} : arguments[3];

  if (!state) {
    $log.debug('[native transition] cannot change state without a state...');
    return;
  }
  unregisterToStateChangeStartEvent();
	transition(transitionOptions);
	if (ionic.Platform.isIOS()) {
    $timeout(function() {
			$state.go(state, stateParams, stateOptions);
		});
	} else {
		$state.go(state, stateParams, stateOptions);
	}
}
```

I decided to add the check for an iOS device and run the timeout only in that case because it was only occurring in iOS devices and the timeout perhaps made Android devices flicker a little on the transition (I could be paranoid and this not really even occurring, or is due to large images on the content on my app).

Same fix probably also works in the case that you are using locationurl instead in which case you just set timeout to the "$location.url(url);" function.

Not sure if this would be the final solution for this problem but it works for now.

**Comment by tskweres** [comment]
My header title and back buttons etc don't animate anymore after fixing this with a $timeout. I'm using fixedPixelsTop but of course the title and header buttons just appear after the animation is over. 

Any idea on how to use fixedPixelsTop but still take advantage of header elements animation?

**Comment by DaDanny** [comment]
This is what fixed it for me:

https://github.com/shprink/ionic-native-transitions/issues/97#issuecomment-220991408


iosdelay = -1

**Comment by tosmos** [comment]
Please help me.
Transition A to B.
It shows B first and transition A to B
How to solve this problem.
